### ISSUE TITLE
Sending mail is broken 

### ISSUE THREAD

**Issue by sylvestre** [mozilla/relman-auto-nag#121]
```
Traceback (most recent call last):
  File "/home/sylvestre/dev/mozilla/relman-auto-nag/auto_nag/scripts/email_nag.py", line 451, in <module>
    dryrun=options.dryrun)
  File "/home/sylvestre/dev/mozilla/relman-auto-nag/auto_nag/mail.py", line 61, in sendMail
    mailserver = smtplib.SMTP(SMTP, PORT)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 318, in connect
    (code, msg) = self.getreply()
  File "/usr/lib/python2.7/smtplib.py", line 369, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed

```

git revert 9314a3841569ff5bcde69288aaf260e492f03185
fixed my issue

**Comment by sylvestre** [comment]
Ditto for the no assignee:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/sylvestre/dev/mozilla/relman-auto-nag/auto_nag/scripts/no_assignee.py", line 148, in <module>
    send_email(date=args.date, dryrun=args.dryrun)
  File "/home/sylvestre/dev/mozilla/relman-auto-nag/auto_nag/scripts/no_assignee.py", line 133, in send_email
    html=True, login=login_info, dryrun=dryrun)
  File "auto_nag/mail.py", line 56, in send
    mailserver = smtplib.SMTP(SMTP, PORT)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 318, in connect
    (code, msg) = self.getreply()
  File "/usr/lib/python2.7/smtplib.py", line 369, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed

```
