### ISSUE TITLE
Issue on the merge day time frame

### ISSUE THREAD

**Issue by sylvestre** [mozilla/relman-auto-nag#146]
```
Traceback (most recent call last):
  File "/home/sylvestre/dev/mozilla/relman-auto-nag/auto_nag/scripts/email_nag.py", line 420, in <module>
    cc_only=options.cc_only)
  File "/home/sylvestre/dev/mozilla/relman-auto-nag/auto_nag/scripts/email_nag.py", line 105, in generateEmailOutput
    'affected': bug.get_fx_affected_versions()
  File "/home/sylvestre/dev/mozilla/relman-auto-nag/auto_nag/bugzilla/models.py", line 124, in get_fx_affected_versions
    if self.api_data['cf_status_firefox' + version] == 'affected':
KeyError: u'cf_status_firefox59'
```

I guess it is because fx 59 flags have been removed too early
https://bugzilla.mozilla.org/show_bug.cgi?id=1459643

**Comment by jcristau** [comment]
Sounds like we should make this self.api_data.get('cf_status_firefox' + version, None) == 'affected' e.g. to be robust against this kind of thing.
