### ISSUE TITLE
Employees with unlinked Bugzilla accounts

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/relman-auto-nag#1529]
When an employee does not use their Mozilla email for Bugzilla and at the same time, their Bugzilla email is not linked in the phonebook (e.g., https://people.mozilla.org/p/masayuki-nakano). This causes some tools to fail:

```
2022-07-11 12:07:48,210 - ERROR - Tool no_severity
Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 738, in run
    self.send_email(date=date)
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 671, in send_email
    title, body = self.get_email(date)
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 632, in get_email
    data = self.get_email_data(date, bug_ids)
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 623, in get_email_data
    bugs = self.get_bugs(date=date, bug_ids=bug_ids)
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 442, in get_bugs
    timeout=self.get_config("bz_query_timeout"),
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/bugzilla.py", line 176, in wait
    self.wait_bugs()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/bugzilla.py", line 187, in wait_bugs
    r.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 653, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/bugzilla.py", line 552, in __bugs_cb
    self.bughandler.handle(bug)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/handler.py", line 15, in handle
    self.handler(*args)
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 324, in bughandler
    auto_ni = self.get_mail_to_auto_ni(bug)
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/workflow/no_severity.py", line 75, in get_mail_to_auto_ni
    mail, nick = self.round_robin.get(bug, self.date)
  File "/home/rm_bot/relman-auto-nag/auto_nag/round_robin.py", line 174, in get
    nick = self.get_nick(bzmail, pc, cal)
  File "/home/rm_bot/relman-auto-nag/auto_nag/round_robin.py", line 132, in get_nick
    BugzillaUser(user_names=[bzmail], user_handler=handler).wait()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/connection.py", line 134, in wait
    r.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 653, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/connection.py", line 123, in cb
    res.raise_for_status()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://bugzilla.mozilla.org/rest/user?include_fields=_default&names=mnakano.birchill%40mozilla.com
```

**Comment by suhaibmujahid** [comment]
As discussed with @marco-c  and @calixteman on Matrix, we could have a tool to email the employee and ask them to link their Bugzilla account. Their manager could be added to the CC.

**Comment by suhaibmujahid** [comment]
#1697 fixes cases where an employee uses their primary Mozilla email in Bugzilla without linking it to their profile on PMO. However, it does not cover cases where the employees use their Mozilla email alias for their Bugzilla account.

For example, [Ed Guloien](https://people.mozilla.org/p/edgul) uses his Mozilla email alias for his Bugzilla account (i.e., edgul@mozilla.com) instead of his primary email (i.e., eguloien@mozilla.com), and at the same time, his Bugzilla account is not linked in PMO.

```
2022-11-04 12:00:20,045 - ERROR - Cannot update the triage owner for 'Core::DOM: Networking' to be 'eguloien@mozilla.com': 400 Client Error: Bad Request for url: https://bugzilla.mozilla.org/rest/component?product=Core&component=DOM%3A+Networking
Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/triage_owner_rotations.py", line 61, in _update_triage_owners
    self._put_new_triage_owner(new_triager)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/tenacity/__init__.py", line 326, in wrapped_f
    return self(f, *args, **kw)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/tenacity/__init__.py", line 406, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/tenacity/__init__.py", line 351, in iter
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/tenacity/__init__.py", line 409, in __call__
    result = fn(*args, **kwargs)
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/triage_owner_rotations.py", line 83, in _put_new_triage_owner
    ).put(change)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/bugzilla.py", line 1126, in put
    response.raise_for_status()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
```

**Comment by suhaibmujahid** [comment]
> As discussed with @marco-c and @calixteman on Matrix, we could have a tool to email the employee and ask them to link their Bugzilla account. Their manager could be added to the CC.

The question now is how to identify employees that should have a Bugzilla account. The following are some options:
1. Based on the title: it could be hard since we have 703 unique titles.
1. Based on the team name: one of the limitations is that team names from PMO do not match the ones in [team_managers.json](https://github.com/mozilla/relman-auto-nag/blob/master/auto_nag/scripts/configs/team_managers.json).
1. Cost centers: we need a list of the eligible ones.
1. The superiors: an employee will be required to have a Bugzilla account if one of the managers in [team_managers.json](https://github.com/mozilla/relman-auto-nag/blob/master/auto_nag/scripts/configs/team_managers.json) is their superior (director or indirect).

@marco-c wdyt?

**Comment by marco-c** [comment]
4 sounds like the best bet.
