### ISSUE TITLE
Employees with outdated Bugzilla email on PMO

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/relman-auto-nag#1609]
When a person changes their Bugzilla email after having their Bugzilla account linked to PMO, this leaves PMO with an outdated email (e.g., https://people.mozilla.org/p/krosylight). Such a case causes tools that lookup Bugzilla email from PMO to fail:

```
2022-08-04 12:58:06,846 - INFO - The triage owner for 'Core::DOM: Content Processes' will be: 'saschanaz@outlook.com'
2022-08-04 12:58:07,026 - ERROR - Cannot update the triage owner for 'Core::DOM: Content Processes' to be 'saschanaz@outlook.com': 400 Client Error: Bad Request for url: https://bugzilla.mozilla.org/rest/component?product=Core&component=DOM%3A+Content+Processes
Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/triage_owner_rotations.py", line 61, in _update_triage_owners
    self._put_new_triage_owner(new_triager)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/tenacity/__init__.py", line 349, in iter
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/triage_owner_rotations.py", line 83, in _put_new_triage_owner
    ).put(change)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/bugzilla.py", line 1119, in put
    response.raise_for_status()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://bugzilla.mozilla.org/rest/component?product=Core&component=DOM%3A+Content+Processes
```

**Comment by suhaibmujahid** [comment]
See #1529

**Comment by suhaibmujahid** [comment]
Similar case happens when a user changes their account while keeping the link to the old one in PMO. For example, [Atila Butkovits](https://people.mozilla.org/p/p--3h9ia463kmcayophrjx1us) links to [atila.butkovits@softvision.com](https://bugzilla.mozilla.org/user_profile?user_id=661665); however, the active account is [abutkovits@mozilla.com](https://bugzilla.mozilla.org/user_profile?user_id=661920).

```
2022-08-04 23:31:25,571 - ERROR - Tool fuzzing_bisection_without_regressed_by
Traceback (most recent call last):
  File "/Users/smujahid/repos/mozilla/relman-auto-nag/auto_nag/bzcleaner.py", line 746, in run
    self.send_email(date=date)
  File "/Users/smujahid/repos/mozilla/relman-auto-nag/auto_nag/bzcleaner.py", line 679, in send_email
    title, body = self.get_email(date)
  File "/Users/smujahid/repos/mozilla/relman-auto-nag/auto_nag/bzcleaner.py", line 640, in get_email
    data = self.get_email_data(date, bug_ids)
  File "/Users/smujahid/repos/mozilla/relman-auto-nag/auto_nag/bzcleaner.py", line 631, in get_email_data
    bugs = self.get_bugs(date=date, bug_ids=bug_ids)
  File "/Users/smujahid/repos/mozilla/relman-auto-nag/auto_nag/scripts/fuzzing_bisection_without_regressed_by.py", line 250, in get_bugs
    bugs = self.find_regressor_or_needinfo_target(bugs)
  File "/Users/smujahid/repos/mozilla/relman-auto-nag/auto_nag/scripts/fuzzing_bisection_without_regressed_by.py", line 215, in find_regressor_or_needinfo_target
    users = UserActivity(include_fields=["nick"]).get_bz_users_with_status(
  File "/Users/smujahid/repos/mozilla/relman-auto-nag/auto_nag/user_activity.py", line 143, in get_bz_users_with_status
    BugzillaUser(
  File "/Users/smujahid/repos/mozilla/relman-auto-nag/venv/lib/python3.9/site-packages/libmozdata/connection.py", line 134, in wait
    r.result()
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/smujahid/repos/mozilla/relman-auto-nag/venv/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/smujahid/repos/mozilla/relman-auto-nag/venv/lib/python3.9/site-packages/requests/sessions.py", line 708, in send
    r = dispatch_hook("response", hooks, r, **kwargs)
  File "/Users/smujahid/repos/mozilla/relman-auto-nag/venv/lib/python3.9/site-packages/requests/hooks.py", line 30, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/Users/smujahid/repos/mozilla/relman-auto-nag/venv/lib/python3.9/site-packages/libmozdata/connection.py", line 123, in cb
    res.raise_for_status()
  File "/Users/smujahid/repos/mozilla/relman-auto-nag/venv/lib/python3.9/site-packages/requests/models.py", line 1022, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://bugzilla.mozilla.org/rest/user?include_fields=name&include_fields=can_login&include_fields=last_activity_time&include_fields=last_seen_date&include_fields=nick&names=botond%40mozilla.com&names=jwatt%40jwatt.org&names=hikezoe.birchill%40mozilla.com&names=atila.butkovits%40softvision.com&names=pbone%40mozilla.com&names=nalexander%40mozilla.com&names=m_kato%40ga2.so-net.ne.jp
```

```
{
  "error": true,
  "code": 51,
  "documentation": "https://bmo.readthedocs.io/en/latest/api/",
  "message": "There is no user named 'atila.butkovits@softvision.com'. Either you mis-typed the name or that user has not yet registered for a Bugzilla account."
}
```

**Comment by marco-c** [comment]
We could build a single tool to cover this and #1529.

**Comment by suhaibmujahid** [comment]
> We could build a single tool to cover this and #1529.

For this part of the problem, when we update `pepole.json`, we could query Bugzilla using the user id to get the valid Bugzilla email. In this way, we mitigate the problem silently. Ideally, PMO should be taking care of this issue.

In the case of #1529 and #1677, we need a tool to email the people to link their Bugzilla accounts. However, based on the discussion @globau and @dklawren on [Slcak (#iam)](https://mozilla.slack.com/archives/CBT3XRZKP/p1659971987955799), these two issues should be mitigated once BMO integrates with IAM is landed.
