### ISSUE TITLE
DOM Core bugzilla triage owner isn't consistent with the DOM Core triage rotation calendar

### ISSUE THREAD

**Issue by hsinyi** [mozilla/relman-auto-nag#1655]
Hi,
According to DOM Core team triage rotation calendar, 
Henri Sivonen was at the triage duty for the week of Sep. 12, and Masayuki Nakano is for this week, i.e. week of Sep. 19.

The autonag email "[autonag] Bugs to triage for the 2022-09-19/2022-09-20" works right that it was sent to Masayuki. However, the triage owner shown on bugzilla components was still Henri Sivonen.

My understanding is that the calendar, autonag email and the bugzilla triage owner should be consistent. Please take a look. Thanks!

**Comment by suhaibmujahid** [comment]
This happens because Masayuki's Bugzilla account is not linked to his PMO profile (https://people.mozilla.org/p/masayuki-nakano). As a result, autonag tries to use his Mozilla email to set him as a triage owner. However, since that email is not linked to a Bugzilla account, it fails:

```
2022-09-20 12:00:19,091 - ERROR - Cannot update the triage owner for 'Core::DOM: Bindings (WebIDL)' to be 'mnakano.birchill@mozilla.com': 400 Client Error: Bad Request for url: https://bugzilla.mozilla.org/rest/component?product=Core&component=DOM%3A+Bindings+%28WebIDL%29
Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/triage_owner_rotations.py", line 61, in _update_triage_owners
    self._put_new_triage_owner(new_triager)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/tenacity/__init__.py", line 349, in iter
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/triage_owner_rotations.py", line 83, in _put_new_triage_owner
    ).put(change)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/bugzilla.py", line 1126, in put
    response.raise_for_status()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://bugzilla.mozilla.org/rest/component?product=Core&component=DOM%3A+Bindings+%28WebIDL%29
```

This is reported in #1529 and discussed on Slack [here](https://mozilla.slack.com/archives/CBT3XRZKP/p1659974177387169?thread_ts=1659971987.955799&cid=CBT3XRZKP).

**Comment by hsinyi** [comment]
Thank you. I'll work with Masayuki to correct the link part.

**Comment by marco-c** [comment]
Similar issue as https://github.com/mozilla/bugzilla-dashboard/issues/224, https://github.com/mozilla/bugbot/issues/1699 will help prevent this kind of problem.
