### ISSUE TITLE
[reminder] Cannot import name 'ParserError' from 'dateutil.parser'

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/relman-auto-nag#1845]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/reminder.py", line 7, in <module>
    from dateutil.parser import ParserError
ImportError: cannot import name 'ParserError' from 'dateutil.parser' (/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/dateutil/parser/__init__.py)
```

**Comment by suhaibmujahid** [comment]
`ParserError` was added in `python-dateutil` v2.8.1, we have v2.5.2 installed: https://dateutil.readthedocs.io/en/stable/parser.html#dateutil.parser.ParserError
