### ISSUE TITLE
Release mgmt bot is no longer setting bug's affected versions based on the regressor

### ISSUE THREAD

**Issue by DonalMe** [mozilla/relman-auto-nag#1864]
For the last day or so, the affected/unaffected versions on regressions have not been set by the bot:
Examples:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1814812
- https://bugzilla.mozilla.org/show_bug.cgi?id=1814821

Some additional info:
> From the Status email: "i updated status flags on the following bugs" and then a list that's essentially the same every hour, except the flags aren't actually changed

**Comment by DonalMe** [comment]
FYI @suhaibmujahid

**Comment by suhaibmujahid** [comment]
```
2023-02-07 16:33:08,938 - CRITICAL - Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/multifix_regression.py", line 66, in <module>
    MultiFixRegressed().run()
  File "/home/rm_bot/relman-auto-nag/auto_nag/multi_autofixers.py", line 108, in run
    new_changes = self._merge_changes_from_tools()
  File "/home/rm_bot/relman-auto-nag/auto_nag/multi_autofixers.py", line 140, in _merge_changes_from_tools
    tools_with_common_field
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/multifix_regression.py", line 47, in __merge_comment
    raise UnexpectedToolsError(list(tools))
auto_nag.multi_autofixers.UnexpectedToolsError: <unprintable UnexpectedToolsError object>
```
