### ISSUE TITLE
Failing to create bugs for some expiring variants

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/relman-auto-nag#1872]
Reported by @jmaher 

```
2023-02-06 12:21:35,309 - ERROR - Failed to create a bug for the variant `fission`
Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/variant_expiration.py", line 183, in get_bugs
    bug = utils.create_bug(new_bug)
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 748, in create_bug
    resp.raise_for_status()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://bugzilla.mozilla.org/rest/bug
2023-02-06 12:21:37,577 - ERROR - Failed to create a bug for the variant `no-fission`
Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/variant_expiration.py", line 183, in get_bugs
    bug = utils.create_bug(new_bug)
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 748, in create_bug
    resp.raise_for_status()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://bugzilla.mozilla.org/rest/bug
2023-02-06 12:21:39,885 - ERROR - Failed to create a bug for the variant `conditioned_profile`
Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/variant_expiration.py", line 183, in get_bugs
    bug = utils.create_bug(new_bug)
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 748, in create_bug
    resp.raise_for_status()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://bugzilla.mozilla.org/rest/bug
2023-02-06 12:21:42,178 - ERROR - Failed to create a bug for the variant `webgl-ipc`
Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/variant_expiration.py", line 183, in get_bugs
    bug = utils.create_bug(new_bug)
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 748, in create_bug
    resp.raise_for_status()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://bugzilla.mozilla.org/rest/bug
```

**Comment by jmaher** [comment]
I wonder if we have small typos in the bug product/component?

**Comment by suhaibmujahid** [comment]
Here are the error details from BMO (cc @dklawren):


## `fission`

Request:
```json
{
  "summary": "The variant `fission` expiration is on 2023-03-01",
  "product": "Testing",
  "component": "General",
  "status_whiteboard": "[variant-expiration]",
  "type": "task",
  "see_also": [],
  "cc": ["jmaher@mozilla.com", "smujahid@mozilla.com"],
  "description": "\nIf the variant is not used anymore, please drop it from the [variants.yml](https://searchfox.org/mozilla-central/source/taskcluster/ci/test/variants.yml) file. If there is a need to keep the variant, please submit a patch to modify the expiration date. Variants will not be scheduled to run after the expiration date.\n\nThis bug will be closed automatically once the variant is dropped or the expiration date is updated in the [variants.yml](https://searchfox.org/mozilla-central/source/taskcluster/ci/test/variants.yml) file.\n\nMore information about variants can be found on [Firefox Source Docs](https://firefox-source-docs.mozilla.org/taskcluster/kinds/test.html#variants).\n\n_Note: please do not edit the bug summery or close the bug, it could break the automation._\n"
}

```
Response:
```json
{
  "message": "The version value 'Version 3' is not active.",
  "documentation": "https://bmo.readthedocs.io/en/latest/api/",
  "code": 32000,
  "error": true
}
```

## `no-fission`

Request:
```json
{
  "summary": "The variant `no-fission` expiration is on 2023-03-01",
  "product": "Testing",
  "component": "General",
  "status_whiteboard": "[variant-expiration]",
  "type": "task",
  "see_also": [],
  "cc": ["jmaher@mozilla.com", "smujahid@mozilla.com"],
  "description": "\nIf the variant is not used anymore, please drop it from the [variants.yml](https://searchfox.org/mozilla-central/source/taskcluster/ci/test/variants.yml) file. If there is a need to keep the variant, please submit a patch to modify the expiration date. Variants will not be scheduled to run after the expiration date.\n\nThis bug will be closed automatically once the variant is dropped or the expiration date is updated in the [variants.yml](https://searchfox.org/mozilla-central/source/taskcluster/ci/test/variants.yml) file.\n\nMore information about variants can be found on [Firefox Source Docs](https://firefox-source-docs.mozilla.org/taskcluster/kinds/test.html#variants).\n\n_Note: please do not edit the bug summery or close the bug, it could break the automation._\n"
}
```

Response:
```json
{
  "error": true,
  "code": 32000,
  "documentation": "https://bmo.readthedocs.io/en/latest/api/",
  "message": "The version value 'Version 3' is not active."
}
```

## `conditioned_profile`

Request:
```json
{
  "summary": "The variant `conditioned_profile` expiration is on 2023-03-01",
  "product": "Testing",
  "component": "General",
  "status_whiteboard": "[variant-expiration]",
  "type": "task",
  "see_also": [],
  "cc": ["jmaher@mozilla.com", "smujahid@mozilla.com"],
  "description": "\nIf the variant is not used anymore, please drop it from the [variants.yml](https://searchfox.org/mozilla-central/source/taskcluster/ci/test/variants.yml) file. If there is a need to keep the variant, please submit a patch to modify the expiration date. Variants will not be scheduled to run after the expiration date.\n\nThis bug will be closed automatically once the variant is dropped or the expiration date is updated in the [variants.yml](https://searchfox.org/mozilla-central/source/taskcluster/ci/test/variants.yml) file.\n\nMore information about variants can be found on [Firefox Source Docs](https://firefox-source-docs.mozilla.org/taskcluster/kinds/test.html#variants).\n\n_Note: please do not edit the bug summery or close the bug, it could break the automation._\n"
}
```

Response:
```json
{
  "message": "The version value 'Version 3' is not active.",
  "documentation": "https://bmo.readthedocs.io/en/latest/api/",
  "code": 32000,
  "error": true
}
```

## `webgl-ipc`

Request:
```json
{
  "summary": "The variant `webgl-ipc` expiration is on 2023-03-01",
  "product": "Core",
  "component": "Canvas: WebGL",
  "status_whiteboard": "[variant-expiration]",
  "type": "task",
  "see_also": [],
  "cc": ["jmaher@mozilla.com", "smujahid@mozilla.com"],
  "description": "\nIf the variant is not used anymore, please drop it from the [variants.yml](https://searchfox.org/mozilla-central/source/taskcluster/ci/test/variants.yml) file. If there is a need to keep the variant, please submit a patch to modify the expiration date. Variants will not be scheduled to run after the expiration date.\n\nThis bug will be closed automatically once the variant is dropped or the expiration date is updated in the [variants.yml](https://searchfox.org/mozilla-central/source/taskcluster/ci/test/variants.yml) file.\n\nMore information about variants can be found on [Firefox Source Docs](https://firefox-source-docs.mozilla.org/taskcluster/kinds/test.html#variants).\n\n_Note: please do not edit the bug summery or close the bug, it could break the automation._\n"
}
```

Response:
```json
{
  "error": true,
  "documentation": "https://bmo.readthedocs.io/en/latest/api/",
  "message": "There is no component named 'Canvas: WebGL' in the 'Core' product.",
  "code": 51
}
```

BTW. It works on bugzilla-dev.allizom.org but not bugzilla.mozilla.org.

**Comment by jmaher** [comment]
I bet testing::general has different parameters/requirements than the other components. 

webgl, should be `Graphics: CanvasWebGL `, I guess that changed in the last 6 months or so.

**Comment by jmaher** [comment]
if we can manually hack this for now, when we update the expiration we can update `Graphics: CanvasWebGL ` as well

**Comment by dklawren** [comment]
Products have the ability in Bugzilla to have a default version when one is not specific via the API. Someone has at some point disabled the version 3 but it is still set to be the default for one or more products. We need to either 1) re-activate the versions, 2) change the defaults to something valid or 3) specify the version directly when calling via the API.

**Comment by suhaibmujahid** [comment]
@dklawren what if our tool always passes `unspecified` as a version value in the API request (for all components)? Do you see a downside to doing so?

**Comment by dklawren** [comment]
> 

That should work fine as it is a valid version for most products. I would still like to address the default versions for some products being set to disabled versions but that is another issue.

**Comment by suhaibmujahid** [comment]
Thank you, @dklawren!

 --------

> if we can manually hack this for now, when we update the expiration we can update Graphics: CanvasWebGL as well

@jmaher I hacked it with the following patch. I will open a PR to always add the version (I hope this will not break other components in future)

```diff
diff --git a/auto_nag/scripts/variant_expiration.py b/auto_nag/scripts/variant_expiration.py
index a919514..b90527d 100644
--- a/auto_nag/scripts/variant_expiration.py
+++ b/auto_nag/scripts/variant_expiration.py
@@ -157,7 +157,8 @@ class VariantExpiration(BzCleaner, Nag):
                 or variant_info["expiration"] >= self.open_bug_date
             ):
                 continue

+            if variant_info["component"] == "Core::Canvas: WebGL":
+                variant_info["component"] = "Core::Graphics: CanvasWebGL"
+
             component = ComponentName.from_str(variant_info["component"])
             expiration = variant_info["expiration"].strftime("%Y-%m-%d")
             new_bug = {
@@ -169,6 +170,7 @@ class VariantExpiration(BzCleaner, Nag):
                 "see_also": self.get_related_bug_ids(variant_name),
                 "cc": self.cc_on_bugs,
                 "description": BUG_DESCRIPTION,
+                "version": "unspecified",
             }

             if self.dryrun or self.test_mode:
```
