### ISSUE TITLE
InvalidWiki: Column headers are wrong

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/relman-auto-nag#1886]
```
2023-02-13 00:30:29,750 - CRITICAL - Uncaught exception
Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/release_calendar.py", line 39, in get_calendar
    parser.feed(html)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/wiki_parser.py", line 87, in feed
    HTMLParser.feed(self, data)
  File "/usr/local/lib/python3.7/html/parser.py", line 111, in feed
    self.goahead(0)
  File "/usr/local/lib/python3.7/html/parser.py", line 173, in goahead
    k = self.parse_endtag(i)
  File "/usr/local/lib/python3.7/html/parser.py", line 421, in parse_endtag
    self.handle_endtag(elem)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/wiki_parser.py", line 112, in handle_endtag
    raise StopIteration()
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/nightly_reopened.py", line 49, in <module>
    NightlyReopened().run()
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/nightly_reopened.py", line 12, in __init__
    if not self.init_versions():
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 77, in init_versions
    self.versions = utils.get_checked_versions()
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 511, in get_checked_versions
    if is_merge_day():
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 250, in is_merge_day
    next_merge = get_merge_day()
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 244, in get_merge_day
    cal = get_release_calendar()
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 238, in get_release_calendar
    return rc.get_calendar()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/release_calendar.py", line 52, in get_calendar
    raise InvalidWiki("Column headers are wrong")
libmozdata.wiki_parser.InvalidWiki: Column headers are wrong
2023-02-13 00:30:32,090 - CRITICAL - Uncaught exception
Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/release_calendar.py", line 39, in get_calendar
    parser.feed(html)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/wiki_parser.py", line 87, in feed
    HTMLParser.feed(self, data)
  File "/usr/local/lib/python3.7/html/parser.py", line 111, in feed
    self.goahead(0)
  File "/usr/local/lib/python3.7/html/parser.py", line 173, in goahead
    k = self.parse_endtag(i)
  File "/usr/local/lib/python3.7/html/parser.py", line 421, in parse_endtag
    self.handle_endtag(elem)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/wiki_parser.py", line 112, in handle_endtag
    raise StopIteration()
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/missing_beta_status.py", line 82, in <module>
    MissingBetaStatus().run()
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/missing_beta_status.py", line 13, in __init__
    if not self.init_versions():
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 77, in init_versions
    self.versions = utils.get_checked_versions()
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 511, in get_checked_versions
    if is_merge_day():
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 250, in is_merge_day
    next_merge = get_merge_day()
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 244, in get_merge_day
    cal = get_release_calendar()
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 238, in get_release_calendar
    return rc.get_calendar()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/release_calendar.py", line 52, in get_calendar
    raise InvalidWiki("Column headers are wrong")
libmozdata.wiki_parser.InvalidWiki: Column headers are wrong
2023-02-13 00:31:39,931 - CRITICAL - Uncaught exception
Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/release_calendar.py", line 39, in get_calendar
    parser.feed(html)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/wiki_parser.py", line 87, in feed
    HTMLParser.feed(self, data)
  File "/usr/local/lib/python3.7/html/parser.py", line 111, in feed
    self.goahead(0)
  File "/usr/local/lib/python3.7/html/parser.py", line 173, in goahead
    k = self.parse_endtag(i)
  File "/usr/local/lib/python3.7/html/parser.py", line 421, in parse_endtag
    self.handle_endtag(elem)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/wiki_parser.py", line 112, in handle_endtag
    raise StopIteration()
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/multifix_regression.py", line 69, in <module>
    MultiFixRegressed().run()
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/multifix_regression.py", line 25, in __init__
    RegressionSetStatusFlags(),
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/regression_set_status_flags.py", line 14, in __init__
    if not self.init_versions():
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 77, in init_versions
    self.versions = utils.get_checked_versions()
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 511, in get_checked_versions
    if is_merge_day():
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 250, in is_merge_day
    next_merge = get_merge_day()
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 244, in get_merge_day
    cal = get_release_calendar()
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 238, in get_release_calendar
    return rc.get_calendar()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/release_calendar.py", line 52, in get_calendar
    raise InvalidWiki("Column headers are wrong")
libmozdata.wiki_parser.InvalidWiki: Column headers are wrong
```

**Comment by suhaibmujahid** [comment]
Regressed by: https://wiki.mozilla.org/index.php?title=Release_Management%2FCalendar&type=revision&diff=1245501&oldid=1245484

**Comment by globau** [comment]
If all you need is the merge day, you'll find it in https://product-details.mozilla.org/1.0/firefox_versions.json

**Comment by suhaibmujahid** [comment]
Thank you @globau, we need other things as well: https://github.com/mozilla/libmozdata/blob/0c29fd0f30f1b7c58ca55dc76333cf3a2c6ae18f/libmozdata/release_calendar.py#L58-L66

I will try to migrate to [Firefox Trains](https://whattrainisitnow.com/about/) where possible.

**Comment by suhaibmujahid** [comment]
As a temporary fix, @dsmithpadilla reverted the changes (added back the old table).
