### ISSUE TITLE
ValueError: 'Central' is not in list

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/relman-auto-nag#1903]
This bug was regressed by the recent change to the structure of the [Release Calendar](https://wiki.mozilla.org/Release_Management/Calendar) wiki page.

```
2023-02-23 12:01:25,930 - CRITICAL - Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/missed_uplifts.py", line 118, in <module>
    MissedUplifts().run()
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/missed_uplifts.py", line 20, in __init__
    self.pending_release = utils.get_report_bugs("release", op="?")
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 264, in get_report_bugs
    "q": "approval-mozilla-{}:{}:{}:0:and:".format(channel, op, get_cycle_span())
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 228, in get_cycle_span
    cycle = [search_prev_merge(c["beta"]), c["merge"]]
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 208, in search_prev_merge
    central = table[0].index("Central")
ValueError: 'Central' is not in list
```
```
2023-02-23 12:02:00,364 - ERROR - Tool unlanded_beta
Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 839, in run
    self.send_email(date=date)
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 757, in send_email
    if not self.has_enough_data():
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/unlanded.py", line 71, in has_enough_data
    self.bug_ids = utils.get_report_bugs(self.channel)
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 264, in get_report_bugs
    "q": "approval-mozilla-{}:{}:{}:0:and:".format(channel, op, get_cycle_span())
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 228, in get_cycle_span
    cycle = [search_prev_merge(c["beta"]), c["merge"]]
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 208, in search_prev_merge
    central = table[0].index("Central")
ValueError: 'Central' is not in list
```
```
2023-02-23 12:02:00,367 - ERROR - Tool unlanded_esr
Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 839, in run
    self.send_email(date=date)
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 757, in send_email
    if not self.has_enough_data():
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/unlanded.py", line 69, in has_enough_data
    self.bug_ids = utils.get_report_bugs(self.channel + self.version)
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 264, in get_report_bugs
    "q": "approval-mozilla-{}:{}:{}:0:and:".format(channel, op, get_cycle_span())
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 228, in get_cycle_span
    cycle = [search_prev_merge(c["beta"]), c["merge"]]
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 208, in search_prev_merge
    central = table[0].index("Central")
ValueError: 'Central' is not in list
```

**Comment by suhaibmujahid** [comment]
See also: #1886
