### ISSUE TITLE
ProxyError: MaxRetryError: HTTPSConnectionPool(host='fx-trains.herokuapp.com', port=443)

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/relman-auto-nag#1909]
```
2023-02-27 12:01:32,320 - CRITICAL - Uncaught exception
Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    self._prepare_proxy(conn)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 807, in _prepare_proxy
    conn.connect()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connection.py", line 324, in connect
    self._tunnel()
  File "/usr/local/lib/python3.7/http/client.py", line 911, in _tunnel
    message.strip()))
OSError: Tunnel connection failed: 403 Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='fx-trains.herokuapp.com', port=443): Max retries exceeded with url: /api/release/schedule/?version=nightly (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/missed_uplifts.py", line 118, in <module>
    MissedUplifts().run()
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/missed_uplifts.py", line 20, in __init__
    self.pending_release = utils.get_report_bugs("release", op="?")
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 246, in get_report_bugs
    "q": "approval-mozilla-{}:{}:{}:0:and:".format(channel, op, get_cycle_span())
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 208, in get_cycle_span
    schedule = FirefoxTrains().get_release_schedule("nightly")
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/fx_trains.py", line 33, in get_release_schedule
    return self.__get(api_path)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/fx_trains.py", line 17, in __get
    resp = requests.get(self.URL + path, timeout=10)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='fx-trains.herokuapp.com', port=443): Max retries exceeded with url: /api/release/schedule/?version=nightly (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
```

<details>
  <summary>Simmiler errors</summary>

```
2023-02-27 12:02:05,525 - ERROR - Tool unlanded_beta
Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    self._prepare_proxy(conn)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 807, in _prepare_proxy
    conn.connect()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connection.py", line 324, in connect
    self._tunnel()
  File "/usr/local/lib/python3.7/http/client.py", line 911, in _tunnel
    message.strip()))
OSError: Tunnel connection failed: 403 Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='fx-trains.herokuapp.com', port=443): Max retries exceeded with url: /api/release/schedule/?version=nightly (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 839, in run
    self.send_email(date=date)
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 757, in send_email
    if not self.has_enough_data():
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/unlanded.py", line 71, in has_enough_data
    self.bug_ids = utils.get_report_bugs(self.channel)
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 246, in get_report_bugs
    "q": "approval-mozilla-{}:{}:{}:0:and:".format(channel, op, get_cycle_span())
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 208, in get_cycle_span
    schedule = FirefoxTrains().get_release_schedule("nightly")
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/fx_trains.py", line 33, in get_release_schedule
    return self.__get(api_path)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/fx_trains.py", line 17, in __get
    resp = requests.get(self.URL + path, timeout=10)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='fx-trains.herokuapp.com', port=443): Max retries exceeded with url: /api/release/schedule/?version=nightly (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
```
```
2023-02-27 12:02:05,551 - ERROR - Tool unlanded_esr
Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    self._prepare_proxy(conn)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 807, in _prepare_proxy
    conn.connect()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connection.py", line 324, in connect
    self._tunnel()
  File "/usr/local/lib/python3.7/http/client.py", line 911, in _tunnel
    message.strip()))
OSError: Tunnel connection failed: 403 Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='fx-trains.herokuapp.com', port=443): Max retries exceeded with url: /api/release/schedule/?version=nightly (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 839, in run
    self.send_email(date=date)
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 757, in send_email
    if not self.has_enough_data():
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/unlanded.py", line 69, in has_enough_data
    self.bug_ids = utils.get_report_bugs(self.channel + self.version)
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 246, in get_report_bugs
    "q": "approval-mozilla-{}:{}:{}:0:and:".format(channel, op, get_cycle_span())
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 208, in get_cycle_span
    schedule = FirefoxTrains().get_release_schedule("nightly")
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/fx_trains.py", line 33, in get_release_schedule
    return self.__get(api_path)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/libmozdata/fx_trains.py", line 17, in __get
    resp = requests.get(self.URL + path, timeout=10)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='fx-trains.herokuapp.com', port=443): Max retries exceeded with url: /api/release/schedule/?version=nightly (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
```

</details>

**Comment by suhaibmujahid** [comment]
See https://github.com/mozilla/libmozdata/pull/211

**Comment by suhaibmujahid** [comment]
Fixed
