### ISSUE TITLE
Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden'))

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/relman-auto-nag#2002]
<details>
<summary>Instance of the error in triage_owner_rotations</summary>

```
2023-04-21 12:00:06,285 - CRITICAL - Uncaught exception
Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    self._prepare_proxy(conn)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 807, in _prepare_proxy
    conn.connect()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connection.py", line 324, in connect
    self._tunnel()
  File "/usr/local/lib/python3.7/http/client.py", line 911, in _tunnel
    message.strip()))
OSError: Tunnel connection failed: 403 Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/adapters.py", line 499, in send
    timeout=timeout,
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/auth/transport/requests.py", line 194, in __call__
    method, url, data=body, headers=headers, timeout=timeout, **kwargs
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/triage_owner_rotations.py", line 104, in <module>
    TriageOwnerRotations().run()
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/triage_owner_rotations.py", line 38, in __init__
    self.component_triagers = ComponentTriagers(excluded_teams=excluded_teams)
  File "/home/rm_bot/relman-auto-nag/auto_nag/component_triagers.py", line 30, in __init__
    self.round_robin: RoundRobin = RoundRobin.get_instance()
  File "/home/rm_bot/relman-auto-nag/auto_nag/round_robin.py", line 39, in get_instance
    RoundRobin._instances[None] = RoundRobin()
  File "/home/rm_bot/relman-auto-nag/auto_nag/round_robin.py", line 27, in __init__
    if rotation_definitions is None
  File "/home/rm_bot/relman-auto-nag/auto_nag/round_robin.py", line 223, in __init__
    doc = gc.open_by_key("1EK6iCtdD8KP4UflIHscuZo6W5er2vy_TX7vsmaaBVd4")
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/gspread/client.py", line 170, in open_by_key
    return Spreadsheet(self, {"id": key})
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/gspread/spreadsheet.py", line 34, in __init__
    metadata = self.fetch_sheet_metadata()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/gspread/spreadsheet.py", line 254, in fetch_sheet_metadata
    r = self.client.request("get", url, params=params)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/gspread/client.py", line 86, in request
    timeout=self.timeout,
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/auth/transport/requests.py", line 545, in request
    self.credentials.before_request(auth_request, method, url, request_headers)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/auth/credentials.py", line 135, in before_request
    self.refresh(request)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/oauth2/service_account.py", line 430, in refresh
    request, self._token_uri, assertion
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/oauth2/_client.py", line 304, in jwt_grant
    request, token_uri, body, can_retry=can_retry
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/oauth2/_client.py", line 271, in _token_endpoint_request
    **kwargs
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/oauth2/_client.py", line 213, in _token_endpoint_request_no_throw
    request_succeeded, response_data, retryable_error = _perform_request()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/oauth2/_client.py", line 190, in _perform_request
    method="POST", url=token_uri, headers=headers, body=body, **kwargs
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/auth/transport/requests.py", line 199, in __call__
    six.raise_from(new_exc, caught_exc)
  File "<string>", line 3, in raise_from
google.auth.exceptions.TransportError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
```

</details>

<details>
<summary>Instance of the error in to_triage</summary>

```
2023-04-21 12:00:08,782 - CRITICAL - Uncaught exception
Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    self._prepare_proxy(conn)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 807, in _prepare_proxy
    conn.connect()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connection.py", line 324, in connect
    self._tunnel()
  File "/usr/local/lib/python3.7/http/client.py", line 911, in _tunnel
    message.strip()))
OSError: Tunnel connection failed: 403 Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/adapters.py", line 499, in send
    timeout=timeout,
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/auth/transport/requests.py", line 194, in __call__
    method, url, data=body, headers=headers, timeout=timeout, **kwargs
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/to_triage.py", line 103, in <module>
    ToTriage().run()
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/to_triage.py", line 21, in __init__
    teams=self.get_config("teams", [])
  File "/home/rm_bot/relman-auto-nag/auto_nag/round_robin.py", line 44, in get_instance
    RoundRobin._instances[teams] = RoundRobin(teams=teams)
  File "/home/rm_bot/relman-auto-nag/auto_nag/round_robin.py", line 27, in __init__
    if rotation_definitions is None
  File "/home/rm_bot/relman-auto-nag/auto_nag/round_robin.py", line 223, in __init__
    doc = gc.open_by_key("1EK6iCtdD8KP4UflIHscuZo6W5er2vy_TX7vsmaaBVd4")
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/gspread/client.py", line 170, in open_by_key
    return Spreadsheet(self, {"id": key})
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/gspread/spreadsheet.py", line 34, in __init__
    metadata = self.fetch_sheet_metadata()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/gspread/spreadsheet.py", line 254, in fetch_sheet_metadata
    r = self.client.request("get", url, params=params)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/gspread/client.py", line 86, in request
    timeout=self.timeout,
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/auth/transport/requests.py", line 545, in request
    self.credentials.before_request(auth_request, method, url, request_headers)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/auth/credentials.py", line 135, in before_request
    self.refresh(request)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/oauth2/service_account.py", line 430, in refresh
    request, self._token_uri, assertion
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/oauth2/_client.py", line 304, in jwt_grant
    request, token_uri, body, can_retry=can_retry
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/oauth2/_client.py", line 271, in _token_endpoint_request
    **kwargs
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/oauth2/_client.py", line 213, in _token_endpoint_request_no_throw
    request_succeeded, response_data, retryable_error = _perform_request()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/oauth2/_client.py", line 190, in _perform_request
    method="POST", url=token_uri, headers=headers, body=body, **kwargs
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/auth/transport/requests.py", line 199, in __call__
    six.raise_from(new_exc, caught_exc)
  File "<string>", line 3, in raise_from
google.auth.exceptions.TransportError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
```

</details>

<details>
<summary>Instance of the error in no_severity</summary>

```
2023-04-21 12:06:11,826 - CRITICAL - Uncaught exception
Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    self._prepare_proxy(conn)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 807, in _prepare_proxy
    conn.connect()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connection.py", line 324, in connect
    self._tunnel()
  File "/usr/local/lib/python3.7/http/client.py", line 911, in _tunnel
    message.strip()))
OSError: Tunnel connection failed: 403 Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/adapters.py", line 499, in send
    timeout=timeout,
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/auth/transport/requests.py", line 194, in __call__
    method, url, data=body, headers=headers, timeout=timeout, **kwargs
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/workflow/multi_nag.py", line 37, in <module>
    wmn = WorkflowMultiNag()
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/workflow/multi_nag.py", line 19, in __init__
    NoSeverity("first"),
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/workflow/no_severity.py", line 37, in __init__
    self.round_robin = RoundRobin.get_instance()
  File "/home/rm_bot/relman-auto-nag/auto_nag/round_robin.py", line 39, in get_instance
    RoundRobin._instances[None] = RoundRobin()
  File "/home/rm_bot/relman-auto-nag/auto_nag/round_robin.py", line 27, in __init__
    if rotation_definitions is None
  File "/home/rm_bot/relman-auto-nag/auto_nag/round_robin.py", line 223, in __init__
    doc = gc.open_by_key("1EK6iCtdD8KP4UflIHscuZo6W5er2vy_TX7vsmaaBVd4")
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/gspread/client.py", line 170, in open_by_key
    return Spreadsheet(self, {"id": key})
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/gspread/spreadsheet.py", line 34, in __init__
    metadata = self.fetch_sheet_metadata()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/gspread/spreadsheet.py", line 254, in fetch_sheet_metadata
    r = self.client.request("get", url, params=params)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/gspread/client.py", line 86, in request
    timeout=self.timeout,
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/auth/transport/requests.py", line 545, in request
    self.credentials.before_request(auth_request, method, url, request_headers)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/auth/credentials.py", line 135, in before_request
    self.refresh(request)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/oauth2/service_account.py", line 430, in refresh
    request, self._token_uri, assertion
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/oauth2/_client.py", line 304, in jwt_grant
    request, token_uri, body, can_retry=can_retry
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/oauth2/_client.py", line 271, in _token_endpoint_request
    **kwargs
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/oauth2/_client.py", line 213, in _token_endpoint_request_no_throw
    request_succeeded, response_data, retryable_error = _perform_request()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/oauth2/_client.py", line 190, in _perform_request
    method="POST", url=token_uri, headers=headers, body=body, **kwargs
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/auth/transport/requests.py", line 199, in __call__
    six.raise_from(new_exc, caught_exc)
  File "<string>", line 3, in raise_from
google.auth.exceptions.TransportError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
```

</details>

<details>
<summary>Instance of the error in triage_rotations_outdated</summary>

```
2023-04-21 12:14:16,715 - ERROR - Tool triage_rotations_outdated
Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    self._prepare_proxy(conn)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 807, in _prepare_proxy
    conn.connect()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connection.py", line 324, in connect
    self._tunnel()
  File "/usr/local/lib/python3.7/http/client.py", line 911, in _tunnel
    message.strip()))
OSError: Tunnel connection failed: 403 Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/adapters.py", line 499, in send
    timeout=timeout,
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/auth/transport/requests.py", line 194, in __call__
    method, url, data=body, headers=headers, timeout=timeout, **kwargs
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 839, in run
    self.send_email(date=date)
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 762, in send_email
    data = self.get_email_data(date)
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/triage_rotations_outdated.py", line 33, in get_email_data
    for row in RotationDefinitions().get_definitions_records():
  File "/home/rm_bot/relman-auto-nag/auto_nag/round_robin.py", line 223, in __init__
    doc = gc.open_by_key("1EK6iCtdD8KP4UflIHscuZo6W5er2vy_TX7vsmaaBVd4")
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/gspread/client.py", line 170, in open_by_key
    return Spreadsheet(self, {"id": key})
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/gspread/spreadsheet.py", line 34, in __init__
    metadata = self.fetch_sheet_metadata()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/gspread/spreadsheet.py", line 254, in fetch_sheet_metadata
    r = self.client.request("get", url, params=params)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/gspread/client.py", line 86, in request
    timeout=self.timeout,
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/auth/transport/requests.py", line 545, in request
    self.credentials.before_request(auth_request, method, url, request_headers)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/auth/credentials.py", line 135, in before_request
    self.refresh(request)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/oauth2/service_account.py", line 430, in refresh
    request, self._token_uri, assertion
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/oauth2/_client.py", line 304, in jwt_grant
    request, token_uri, body, can_retry=can_retry
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/oauth2/_client.py", line 271, in _token_endpoint_request
    **kwargs
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/oauth2/_client.py", line 213, in _token_endpoint_request_no_throw
    request_succeeded, response_data, retryable_error = _perform_request()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/oauth2/_client.py", line 190, in _perform_request
    method="POST", url=token_uri, headers=headers, body=body, **kwargs
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/google/auth/transport/requests.py", line 199, in __call__
    six.raise_from(new_exc, caught_exc)
  File "<string>", line 3, in raise_from
google.auth.exceptions.TransportError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
```

</details>

**Comment by suhaibmujahid** [comment]
Fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1829705
