### ISSUE TITLE
Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/relman-auto-nag#2004]
```
2023-04-21 14:31:08,239 - ERROR - Tool spambug
Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/adapters.py", line 499, in send
    timeout=timeout,
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='[bugbug.herokuapp.com](http://bugbug.herokuapp.com/)', port=443): Max retries exceeded with url: //spambug/predict/batch (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 839, in run
    self.send_email(date=date)
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 762, in send_email
    data = self.get_email_data(date)
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 680, in get_email_data
    bugs = self.get_bugs(date=date)
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/spambug.py", line 75, in get_bugs
    bugs = get_bug_ids_classification("spambug", bug_ids)
  File "/home/rm_bot/relman-auto-nag/auto_nag/bugbug_utils.py", line 37, in get_bug_ids_classification
    response = classification_http_request(url, list(bug_ids))
  File "/home/rm_bot/relman-auto-nag/auto_nag/bugbug_utils.py", line 17, in classification_http_request
    url, headers={"X-Api-Key": "autonag"}, json={"bugs": bug_ids}
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='[bugbug.herokuapp.com](http://bugbug.herokuapp.com/)', port=443): Max retries exceeded with url: //spambug/predict/batch (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
```

**Comment by suhaibmujahid** [comment]
Similar error:

```
2023-04-25 12:31:00,612 - ERROR - Tool regression
Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/adapters.py", line 499, in send
    timeout=timeout,
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='[bugbug.herokuapp.com](http://bugbug.herokuapp.com/)', port=443): Max retries exceeded with url: //regression/predict/batch (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 839, in run
    self.send_email(date=date)
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 762, in send_email
    data = self.get_email_data(date)
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 680, in get_email_data
    bugs = self.get_bugs(date=date)
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/regression.py", line 63, in get_bugs
    bugs = get_bug_ids_classification("regression", bug_ids)
  File "/home/rm_bot/relman-auto-nag/auto_nag/bugbug_utils.py", line 37, in get_bug_ids_classification
    response = classification_http_request(url, list(bug_ids))
  File "/home/rm_bot/relman-auto-nag/auto_nag/bugbug_utils.py", line 17, in classification_http_request
    url, headers={"X-Api-Key": "autonag"}, json={"bugs": bug_ids}
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='[bugbug.herokuapp.com](http://bugbug.herokuapp.com/)', port=443): Max retries exceeded with url: //regression/predict/batch (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
```
