### ISSUE TITLE
new bug type is causing an exception on some bugs

### ISSUE THREAD

**Issue by sylvestre** [mozilla/relman-auto-nag#508]
```
2019-04-03 08:16:54,283 - ERROR - Tool component
Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 520, in run
    self.send_email(date=date, dryrun=args.dryrun)
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 462, in send_email
    title, body = self.get_email(login_info['bz_api_key'], date, dryrun)
  File "/home/rm_bot/relman-auto-nag/auto_nag/bzcleaner.py", line 421, in get_email
    bugs = self.get_bugs(date=date, bug_ids=bug_ids)
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/component.py", line 84, in get_bugs
    probs = self.model.classify(copy.deepcopy(bugs), True)
  File "/home/rm_bot/relman-auto-nag/venv3/lib/python3.6/site-packages/bugbug/model.py", line 170, in classify
    X = self.extraction_pipeline.transform(bugs)
  File "/home/rm_bot/relman-auto-nag/venv3/lib/python3.6/site-packages/sklearn/pipeline.py", line 451, in _transform
    Xt = transform.transform(Xt)
  File "/home/rm_bot/relman-auto-nag/venv3/lib/python3.6/site-packages/bugbug/bug_features.py", line 383, in transform
    bug = bug_snapshot.rollback(bug, self.rollback_when)
  File "/home/rm_bot/relman-auto-nag/venv3/lib/python3.6/site-packages/bugbug/bug_snapshot.py", line 320, in rollback
    assert False, f'Current value for field {field} of {bug["id"]}:\n{bug[field]}\nis different from previous value:\n{new_value}'
AssertionError: Current value for field severity of 1476862:
normal
is different from previous value:
enhancement

```

**Comment by marco-c** [comment]
This is a problem in bugbug. The issue is that the type change is not in the history of the bug, so the history is inconsistent. I'll fix it in bugbug.

**Comment by marco-c** [comment]
Ah no sorry, this is the severity field :/
Anyway, still a bugbug problem.

**Comment by marco-c** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1476862 is inconsistent, severity was changed to `enhancement`, but the bug data still has severity == `normal`. CC @kyoshino

**Comment by marco-c** [comment]
Same with 1465872.

**Comment by marco-c** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1541362.

**Comment by marco-c** [comment]
Ah, I got it. It's because the enhancement severity was disabled, and so it was moved back to normal, but the change is not present in the history of the bugs,
