### ISSUE TITLE
Error when db does not exist

### ISSUE THREAD

**Issue by sylvestre** [mozilla/relman-auto-nag#592]
```
    
    <p>
      See the source / report issues on the <a href="https://github.com/mozilla/relman-auto-nag/">GitHub repo</a>
    </p>
  </body>
</html>
--===============3422918664075064949==--

2019-04-22 14:52:48,207 - INFO - Lock 139691430382352 acquired on db/lock
2019-04-22 14:52:48,224 - INFO - Lock 139691430382352 released on db/lock
2019-04-22 14:52:48,225 - ERROR - Tool defect_with_please
Traceback (most recent call last):
  File "auto_nag/bzcleaner.py", line 567, in run
    self.send_email(date=date)
  File "auto_nag/bzcleaner.py", line 518, in send_email
    db.Email.add(self.name(), receivers, 'global', status)
  File "auto_nag/db.py", line 341, in add
    tool = Tool.get_or_create(tool)
  File "auto_nag/db.py", line 66, in get_or_create
    return session.query(Tool).filter(Tool.name == name).one()
  File "/home/sylvestre/dev/mozilla/relman-auto-nag/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3275, in one
    ret = self.one_or_none()
  File "/home/sylvestre/dev/mozilla/relman-auto-nag/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3244, in one_or_none
    ret = list(self)
  File "/home/sylvestre/dev/mozilla/relman-auto-nag/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3317, in __iter__
    return self._execute_and_instances(context)
  File "/home/sylvestre/dev/mozilla/relman-auto-nag/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3342, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/sylvestre/dev/mozilla/relman-auto-nag/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/sylvestre/dev/mozilla/relman-auto-nag/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/sylvestre/dev/mozilla/relman-auto-nag/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/sylvestre/dev/mozilla/relman-auto-nag/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/sylvestre/dev/mozilla/relman-auto-nag/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/sylvestre/dev/mozilla/relman-auto-nag/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/sylvestre/dev/mozilla/relman-auto-nag/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/sylvestre/dev/mozilla/relman-auto-nag/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) no such table: autonag_tools
[SQL: SELECT autonag_tools.id AS autonag_tools_id, autonag_tools.name AS autonag_tools_name 
FROM autonag_tools 
WHERE autonag_tools.name = ?]
[parameters: ('defect_with_please',)]
(Background on this error at: http://sqlalche.me/e/e3q8)

```

**Comment by calixteman** [comment]
Fixed: https://github.com/mozilla/relman-auto-nag/pull/596
