### ISSUE TITLE
hide bugzilla user & password in any and all output from scripts

### ISSUE THREAD

**Issue by lsblakk** [mozilla/relman-auto-nag#8]
Currently the logging and screen output for the scripts will show the username & password in the Bugzilla URL output which is not ideal for putting this (eventually) on a shared server.

**Comment by sylvestre** [comment]
FWIW, we moved to api key but this is still a private information.

**Comment by anubnair** [comment]
@sylvestre: I have started working on it. A sample error while parsing invalid api key:

Traceback (most recent call last):
  File "test.py", line 21, in <module>
    buglist = bmo.get_bug_list(options)
  File "/home/bztools/bugzilla/agents.py", line 34, in get_bug_list
    print "(", BugSearch.get(url).bugs
  File "/usr/local/lib/python2.7/dist-packages/remoteobjects/fields.py", line 141, in __get__
    value = obj.api_data[self.api_name]
  File "/usr/local/lib/python2.7/dist-packages/remoteobjects/promise.py", line 136, in _get_api_data
    self.deliver()
  File "/usr/local/lib/python2.7/dist-packages/remoteobjects/promise.py", line 216, in deliver
    self.update_from_response(request['uri'], response, content)
  File "/usr/local/lib/python2.7/dist-packages/remoteobjects/promise.py", line 232, in update_from_response
    super(PromiseObject, self).update_from_response(url, response, content)
  File "/usr/local/lib/python2.7/dist-packages/remoteobjects/http.py", line 263, in update_from_response
    self.raise_for_response(url, response, content)
  File "/usr/local/lib/python2.7/dist-packages/remoteobjects/http.py", line 214, in raise_for_response
    % (response.status, response.reason, classname, url))

remoteobjects.http.RequestError: 400 Bad Request requesting BugSearch https://bugzilla.mozilla.org/bzapi/bug/?&changed_before=2010-12-26&product=Core,Firefox&changed_field=status&changed_after=2010-12-24&include_fields=_default,attachments&changed_field_to=RESOLVED&api_key=**********&resolution=FIXED

Now we are not handling exceptions properly. Thats why we are getting something like this.

2 ways we can avoid logging and screen output:

1) Mask the api key(replace with ****)  similar to:

 Remoteobjects.http.RequestError: 400 Bad Request requesting BugSearch https://bugzilla.mozilla.org/bzapi/bug/?&changed_before=2010-12-26&product=Core,Firefox&changed_field=status&changed_after=2010-12-24&include_fields=_default,attachments&changed_field_to=RESOLVED&api_key=**********&resolution=FIXED

2) We don't need to give url Just print the error similar to:
"400 Bad Request requesting BugSearch "

let me know which one so that I can do the changes.

**Comment by sylvestre** [comment]
Fixed by https://github.com/mozilla/relman-auto-nag/pull/35
