### ISSUE TITLE
Support running scripts without a people.json

### ISSUE THREAD

**Issue by marco-c** [mozilla/relman-auto-nag#887]
E.g. if I run the spambug model:
```
2020-02-05 12:07:52,126 - INFO - Run tool spambug.py
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/marco/Documenti/workspace/relman-auto-nag/auto_nag/scripts/spambug.py", line 95, in <module>
    SpamBug().run()
  File "/home/marco/Documenti/workspace/relman-auto-nag/auto_nag/scripts/spambug.py", line 14, in __init__
    self.people = people.People.get_instance()
  File "/home/marco/Documenti/workspace/relman-auto-nag/auto_nag/people.py", line 58, in get_instance
    People._instance = People()
  File "/home/marco/Documenti/workspace/relman-auto-nag/auto_nag/people.py", line 37, in __init__
    with open("./auto_nag/scripts/configs/people.json", "r") as In:
FileNotFoundError: [Errno 2] No such file or directory: './auto_nag/scripts/configs/people.json'
```

**Comment by calixteman** [comment]
We could have a fake people.json we use as a fallback and in this case we shouldn't send any emails or update bugs (just in case).
@marco-c Wdyt ?

**Comment by marco-c** [comment]
Yeah, that sounds good to me.
